### ISSUE TITLE
Оформление тумблера

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-android#13]
Поменялись цвета, смайлики меняем на слова (из файла с текстами). 

Попроси Антона сделать нарезку.

**Comment by suntehnik** [comment]
можно вместо теста сделать картинку с текстом? А то править 30 файлов если честно очень лениво. А подменить 2 картинки на которые ссылаются ресурсы - дело 2-х минут.

**Comment by infotanka** [comment]
В том то и дело, что там тексты где-то «да-нет», а где-то «нет-да»,
или даже «есть-нет». Так что в файлы всё равно придётся лезть :-(

Лучше всё-таки тексты, мне кажется. Прикрутить из plist'а того же.

2012/2/20 suntehnik
reply@reply.github.com:

> можно вместо теста сделать картинку с текстом? А то править 30 файлов если честно очень лениво. А подменить 2 картинки на которые ссылаются ресурсы - дело 2-х минут.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webnabludatel/watcher-android/issues/13#issuecomment-4050881

## 

Таня Мисютина, http://infotanka.ru

**Comment by suntehnik** [comment]
ок. просто прикрутить из plist-а означает copy-paste.
У меня совсем другие форматы xml
