### ISSUE TITLE
Шаринг Отчета в фейсбук возвращает на пустой экран отчета (null написано)

### ISSUE THREAD

**Issue by aefimov** [webnabludatel/watcher-android#19]
И при этом ничего конечно не шарит

**Comment by suntehnik** [comment]
проблема скорее всего в настройках твоего телефона - настрой синхронизацию с FaceBook в HTC Sense

**Comment by suntehnik** [comment]
был баг в коде FB. Отключил возможность авторизации через встроенные приложения - все заработало.
