### ISSUE TITLE
приложение периодически падает.  

### ISSUE THREAD

**Issue by len4ik83** [webnabludatel/watcher-android#29]
падение произошло при нажатии "Ваш отчет на сайте" на табе Отчет.

google nexus s v.4.0.3

лог:
03-01 13:15:56.742: I/wpa_supplicant(25220): wlan0: CTRL-EVENT-CONNECTED - Connection to 00:1d:e5:80:9d:11 completed (reauth) [id=0 id_str=]
03-01 13:15:58.304: W/dalvikvm(25138): threadid=11: thread exiting with uncaught exception (group=0x40a4f1f8)
03-01 13:15:58.394: E/AndroidRuntime(25138): FATAL EXCEPTION: Timer-1
03-01 13:15:58.394: E/AndroidRuntime(25138): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:4039)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:2210)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:556)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.View.setFlags(View.java:6712)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.view.View.setVisibility(View.java:4617)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at android.widget.ProgressBar.setVisibility(ProgressBar.java:875)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at org.dvaletin.apps.nabludatel.NabludatelSettingsActivity$2.run(NabludatelSettingsActivity.java:87)
03-01 13:15:58.394: E/AndroidRuntime(25138):    at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by aefimov** [comment]
Исправлено, спасибо!
