### ISSUE TITLE
Табы всегда на экране

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-android#3]
На всех эранах, кроме последнего уровня чеклиста, нужно отображать табы.

Чтобы человек не терялся и всегда мог перейти в нужный раздел.

**Comment by infotanka** [comment]
Сейчас табы пропадают в справочнике — не ок.

**Comment by suntehnik** [comment]
Нужно ли делать вызов справочника из последнего уровня чек-листа? И как это делать?

**Comment by infotanka** [comment]
Нет, от этой идеи отказались, максимально расшифровав пункты чеклиста.

**Comment by aefimov** [comment]
Сделано
