### ISSUE TITLE
при смене участка отчет не обновляется

### ISSUE THREAD

**Issue by len4ik83** [webnabludatel/watcher-android#32]
введены два участка: участок1 и участок2.
1. заполнить нарушения по участку1. посмотреть отчет. (например 3 требования 4 нарушения)
2. сменить участок. заполнить нарушения по участку2. просмотреть отчет (7 требований 4 нарушения)
3. снова выбрать участок1. дополнить нарушения. просмотреть отчет.

AR: отчет показывается по участку2. под графиком написано "Заполните раздел наблюдения". хотя в разделе наблюдения данные сохранились. 

помогает только убить процесс в настройках и запустить снова.

очень похоже, что не всегда отчет обновляется и для одного участка.

**Comment by suntehnik** [comment]
fixed
