### ISSUE TITLE
Требует уточнения

### ISSUE THREAD

**Issue by glader** [webnabludatel/watcher-android#37]
Я наизусть законы не помню, но смущает несколько пунктов
1. Допуск наблюдателей > ознакомление со списком избирателей
   Список избирателей является персональными данными. Могут ли члены УИК показывать его наблюдателям?
2. Помещение для голосования > увеличенный протокол
   Увеличенный протокол вывешивается после закрытия участка
3. Подготовка к началу голосования
   Совсем ничего нет про КОИБы и их тестирование.
4. Подготовка к началу голосования > объявлено кол-во заявлений для голосования на дому
   В этом нет смысла, заявления на дом поступают и в течение дня голосования.
5. Голосование на дому > После возвращения в выписке нет новых фамилий
   Время от времени члены УИК встречают в квартире по вызову дополнительных желающих проголосовать. Обычно после звонка на участок эти желающие получают возможность проголосовать. В законе нет четких критериев возможности голосования на дому.
6. Работа со списком избирателей > наблюдатели приглашены ознакомитсья со списком
   Аналогично пункту 1

**Comment by glader** [comment]
Извините, ошибся с проектом

**Comment by aefimov** [comment]
То то я думаю, что у нас вроде было про КОИБы :)
