### ISSUE TITLE
Индикатор в верхнем правом углу

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-android#6]
В верхнем правом углу, напротив заголовка, появится индикатор синхронизации с сервером.

Как только Илья его прикрутит, я покажу тебе скриншот, как он должен выглядеть. Антона попрошу нарезать картинки.

**Comment by suntehnik** [comment]
Индикатор будет в нотификационной области (а-ля iOS5 при движении пальцем с верхнего края вниз). Это стандартная область андроида для нотификации пользователей.

Правда я еще этого не делал, но оставлю на  последок.

**Comment by aefimov** [comment]
Сделано
