### ISSUE TITLE
Добавление участка в «Чеклисте»

### ISSUE THREAD

**Issue by infotanka** [webnabludatel/watcher-android#8]
Мы с Ильёй решили перенести добавление участка в чеклист.

Можно посмотреть здесь, картинки 03 и 04: https://progress-engine.basecamphq.com/projects/8732853/posts/57783892/comments#162236735

**Comment by infotanka** [comment]
То есть информацию об участке нужно вынести в отдельный блок и сделать возможность добавления новых участков и переключения между ними

**Comment by suntehnik** [comment]
Так я это реализовал уже. Просто из профиля наблюдателя не убрал. Закрываем?

**Comment by infotanka** [comment]
Я видела там один пункт УИК. Можно ли добавить несколько? Как?

**Comment by suntehnik** [comment]
Там кнопка добавить участок. В экране добавления можно выбрать тип: УИК, ТИК, ИКМО

**Comment by suntehnik** [comment]
Выбор между участками реализован через дропдаун (в андроиде он называется спиннер).
При этом все экраны чеклиста переключаются на выбранный участок с запоминанием отдельной истории по каждому участку - это реализованный функционал.

**Comment by infotanka** [comment]
А нельзя ли кнопку «Добавить» вынести на верхний уровень? Как сделано у Ильи.

Остальное ок.
